name: Update TV Channels

on:
  schedule:
    - cron: '0 0 * * *'  # Her gün gece yarısı çalıştır
  workflow_dispatch:  # Manuel olarak da tetiklenebilir

jobs:
  update-channels:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run channel scraper
      run: python channel_scraper.py
      
    - name: Save debug HTML if exists
      run: |
        if [ -f debug_page.html ]; then
          cat debug_page.html > debug_output.txt
          echo "Debug HTML sayfası oluşturuldu"
        fi
      
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Otomatik kanal listesi güncellemesi: $(date +'%Y-%m-%d')"
        file_pattern: "kanallar.m3u metadata.json debug_page.html"
