name: Update TV Channels

on:
  schedule:
    - cron: '0 0 * * *'  # Her gün gece yarısı çalıştır
  workflow_dispatch:  # Manuel olarak da tetiklenebilir

jobs:
  update-channels:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run channel scraper
      run: python channel_scraper.py
      
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add kanallar.m3u metadata.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Otomatik kanal listesi güncellemesi: $(date +'%Y-%m-%d')" && git push) 